// Mock data for files and folders
let files = [
  { id: 1, name: 'Create', type: 'folder', parent_id: null, position_x: 25, position_y: 50, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 2, name: 'Build', type: 'folder', parent_id: null, position_x: 25, position_y: 150, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 3, name: 'Explore', type: 'folder', parent_id: null, position_x: 25, position_y: 250, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 16, name: 'Automate', type: 'folder', parent_id: null, position_x: 125, position_y: 50, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 17, name: 'Learn', type: 'folder', parent_id: null, position_x: 125, position_y: 150, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  // Context folder for Gemini assistant references
  { id: 130, name: 'Context', type: 'folder', parent_id: null, position_x: 120, position_y: 250, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 4, name: 'Video', type: 'file', parent_id: 1, icon: '🎥', url: 'https://studio.freshfront.co' },
  { id: 5, name: 'NFT', type: 'file', parent_id: 1, icon: '🖼️', url: 'https://nft.freshfront.co' },
  { id: 6, name: 'Product', type: 'file', parent_id: 1, icon: '📦', url: 'https://freshfront.co/designer' },
  { id: 7, name: 'Music', type: 'file', parent_id: 1, icon: 'https://kmgahoiiiihmfjnsblij.supabase.co/storage/v1/object/public/music//Mmicon.png.png', url: 'https://musicmigo.com' },
  { id: 8, name: 'Podcast', type: 'file', parent_id: 1, icon: '🎙️', url: 'https://freshfront.co/podcast' },
  { id: 9, name: 'Store', type: 'file', parent_id: 2, icon: '🛍️', url: 'https://freshfront.co' },
  { id: 10, name: 'App', type: 'file', parent_id: 2, icon: '⚙️', url: 'https://build.freshfront.co' },
  { id: 11, name: 'Website', type: 'file', parent_id: 2, icon: '🌐', url: 'https://freshfront.co/page-generator' },
  { id: 12, name: 'Game (coming soon)', type: 'file', parent_id: 2, icon: '🎮' },
  { id: 13, name: 'Search Products', type: 'file', parent_id: 3, icon: '🔍', url: 'https://freshfront.co/search' },
  { id: 14, name: 'Enter Front St.', type: 'file', parent_id: 3, icon: '🏘️', url: '/play' },
  {
    id: 15,
    name: 'Go Shopping',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6794.png',
    category: 'Search & Shop',
    workflow: [
      'Initialize Stripe ‘create a card’ function with user provided credentials',
      'Deploy web scraping agent to target retailer websites',
      'Execute intelligent product search using NLP matching algorithms',
      'Compare prices across multiple platforms in real-time',
      'Add optimal products to cart with quantity optimization',
      'Process automated checkout with fraud detection bypass',
      'Send purchase confirmation with tracking integration',
    ],
    tools: [
      { name: 'Stripe API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6794.png' },
      { name: 'FireCrawl', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6795.png' },
      { name: 'Google', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6826.jpeg' },
      { name: 'Amazon', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6797.png' },
      { name: 'Walmart', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6796.webp' },
      { name: 'AliExpress', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6798.png' },
    ],
    trigger: 'Product request or price threshold alert',
  },
  { id: 18, name: 'Info', type: 'file', parent_id: 17, icon: 'ℹ️', url: '/info' },
  { id: 19, name: 'Store Creation', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 112, name: 'Stripe Onboarding', type: 'file', parent_id: 17, icon: '💳' },
  { id: 20, name: 'Inventory', type: 'folder', parent_id: 19, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 21, name: 'Prompt', type: 'file', parent_id: 20, icon: '💡' },
  { id: 22, name: 'Step by Step', type: 'file', parent_id: 20, icon: '🗺️' },
  { id: 23, name: 'Import', type: 'file', parent_id: 20, icon: '📥' },
  { id: 24, name: 'Print on Demand', type: 'folder', parent_id: 19, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 25, name: 'Prompt', type: 'file', parent_id: 24, icon: '💡' },
  { id: 26, name: 'Step by Step', type: 'file', parent_id: 24, icon: '🗺️' },
  { id: 27, name: 'Import', type: 'file', parent_id: 24, icon: '📥' },
  { id: 28, name: 'Dropshipping', type: 'folder', parent_id: 19, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 29, name: 'Prompt', type: 'file', parent_id: 28, icon: '💡' },
  { id: 30, name: 'Step by Step', type: 'file', parent_id: 28, icon: '🗺️' },
  { id: 31, name: 'Import', type: 'file', parent_id: 28, icon: '📥' },
  { id: 32, name: 'Crowdfunding', type: 'folder', parent_id: 19, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 33, name: 'Prompt', type: 'file', parent_id: 32, icon: '💡' },
  { id: 34, name: 'Step by Step', type: 'file', parent_id: 32, icon: '🗺️' },
  { id: 35, name: 'Import', type: 'file', parent_id: 32, icon: '📥' },
  { id: 36, name: 'Prompt', type: 'file', parent_id: 19, icon: '💡' },
  { id: 37, name: 'Step by Step', type: 'file', parent_id: 19, icon: '🗺️' },
  { id: 38, name: 'Import', type: 'file', parent_id: 19, icon: '📥' },
  { id: 39, name: 'Edit Stores', type: 'file', parent_id: 19, icon: '🖌️' },
  { id: 40, name: 'Products', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 41, name: 'Payments', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 42, name: 'Profiles', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 43, name: 'NFTs', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 44, name: 'Vibe Coding', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 45, name: 'Content Creation', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 46, name: 'AI Tools', type: 'folder', parent_id: 19, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 47, name: 'Automation', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 48, name: 'Marketing', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 49, name: 'Checkout', type: 'file', parent_id: 41, icon: '🛒' },
  { id: 50, name: 'Orders', type: 'file', parent_id: 41, icon: '📋' },
  { id: 51, name: 'Payouts', type: 'file', parent_id: 41, icon: '💵' },
  { id: 52, name: 'Digital Storefront', type: 'file', parent_id: 43, icon: '🏪' },
  { id: 53, name: 'Mint Products', type: 'file', parent_id: 43, icon: '✨' },
  { id: 54, name: 'Avatar', type: 'file', parent_id: 43, icon: '👤' },
  { id: 55, name: 'Front St.', type: 'file', parent_id: 43, icon: '🏘️' },
  { id: 56, name: 'Prompting', type: 'file', parent_id: 44, icon: '💡' },
  { id: 57, name: 'Frameworks', type: 'folder', parent_id: 44, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 58, name: 'Next.js', type: 'file', parent_id: 57, icon: '▶️' },
  { id: 59, name: 'Vite', type: 'file', parent_id: 57, icon: '⚡' },
  { id: 60, name: 'Expo', type: 'file', parent_id: 57, icon: '📱' },
  { id: 61, name: 'Websites', type: 'file', parent_id: 44, icon: '🌐' },
  { id: 62, name: 'Mobile Apps', type: 'file', parent_id: 44, icon: '📱' },
  { id: 63, name: 'Publish', type: 'folder', parent_id: 44, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 64, name: 'App Stores', type: 'file', parent_id: 63, icon: '🛒' },
  { id: 65, name: 'Web Hosting', type: 'file', parent_id: 63, icon: '☁️' },
  { id: 66, name: 'Tavus', type: 'file', parent_id: 45, icon: '🦜' },
  { id: 67, name: 'Generative AI', type: 'folder', parent_id: 45, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 68, name: 'Automated Workflows', type: 'folder', parent_id: 45, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 69, name: 'Customization', type: 'file', parent_id: 42, icon: '🎨' },
  { id: 70, name: 'Posts', type: 'file', parent_id: 42, icon: '✍️' },
  { id: 71, name: 'Link Apps', type: 'file', parent_id: 42, icon: '🔗' },
  { id: 72, name: 'Link Products', type: 'file', parent_id: 42, icon: '🔗' },
  { id: 73, name: 'Shareable Link', type: 'file', parent_id: 42, icon: '🔗' },
  { id: 74, name: 'Import', type: 'file', parent_id: 40, icon: '📥' },
  { id: 75, name: 'POD Designer', type: 'file', parent_id: 40, icon: '👕' },
  { id: 76, name: 'Visualizer', type: 'file', parent_id: 40, icon: '👁️' },
  { id: 77, name: 'Variants', type: 'file', parent_id: 40, icon: '🎨' },
  { id: 78, name: 'Gallery Enhancer', type: 'file', parent_id: 40, icon: '✨' },
  { id: 79, name: 'Mockups', type: 'file', parent_id: 40, icon: '🖼️' },
  { id: 80, name: 'Generation', type: 'file', parent_id: 40, icon: '✨' },
  { id: 81, name: 'Edit', type: 'file', parent_id: 40, icon: '✏️' },
  { id: 82, name: 'Text to Audio', type: 'file', parent_id: 67, icon: '🔊' },
  { id: 83, name: 'Image', type: 'file', parent_id: 67, icon: '🖼️' },
  { id: 84, name: 'Image to Image', type: 'file', parent_id: 67, icon: '🖼️' },
  { id: 85, name: 'Text to Video', type: 'file', parent_id: 67, icon: '🎥' },
  { id: 86, name: 'Image to Video', type: 'file', parent_id: 67, icon: '🎥' },
  { id: 87, name: 'Video to Video', type: 'file', parent_id: 67, icon: '🎥' },
  { id: 88, name: 'Text to 3D', type: 'file', parent_id: 67, icon: '🧊' },
  { id: 89, name: 'Image to 3D', type: 'file', parent_id: 67, icon: '🧊' },
  { id: 90, name: 'Social Media Reel', type: 'file', parent_id: 68, icon: '📱' },
  { id: 91, name: 'YouTube Video', type: 'file', parent_id: 68, icon: '▶️' },
  { id: 92, name: 'Blog Post', type: 'file', parent_id: 68, icon: '✍️' },
  { id: 93, name: 'Product Page', type: 'file', parent_id: 68, icon: '🛍️' },
  { id: 94, name: 'Marketing Campaign', type: 'file', parent_id: 68, icon: '📈' },
  { id: 95, name: 'AI Assistant', type: 'folder', parent_id: 17, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 96, name: 'Custom Instructions', type: 'file', parent_id: 95, icon: '📝' },
  { id: 97, name: 'Knowledge Base', type: 'file', parent_id: 95, icon: '📚' },
  { id: 98, name: 'Customer Personalization', type: 'file', parent_id: 95, icon: '👤' },
  { id: 99, name: 'Voice Mode', type: 'file', parent_id: 95, icon: '🗣️' },
  { id: 100, name: 'Product Recommendations', type: 'file', parent_id: 95, icon: '🛍️' },
  { id: 101, name: 'Email', type: 'file', parent_id: 48, icon: '📧' },
  { id: 102, name: 'Instagram', type: 'file', parent_id: 48, icon: '📸' },
  { id: 103, name: 'TikTok', type: 'file', parent_id: 48, icon: '🎵' },
  { id: 104, name: 'YouTube', type: 'file', parent_id: 48, icon: '▶️' },
  { id: 105, name: 'Google', type: 'folder', parent_id: 48, icon: 'https://images.icon-icons.com/1379/PNG/512/folderblue_92960.png' },
  { id: 106, name: 'Google Ads', type: 'file', parent_id: 105, icon: '📈' },
  { id: 107, name: 'Merchant Center', type: 'file', parent_id: 105, icon: '🛒' },
  { id: 108, name: 'My Business', type: 'file', parent_id: 105, icon: '🏢' },
  { id: 109, name: 'SEO', type: 'file', parent_id: 105, icon: '🔍' },
  { id: 110, name: 'Substack', type: 'file', parent_id: 48, icon: '📚' },
  { id: 111, name: 'X (Twitter)', type: 'file', parent_id: 48, icon: '🐦' },
  {
    id: 113,
    name: 'Build App',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6801.png',
    category: 'Design & Develop',
    workflow: [
      'Generate UI/UX wireframes using AI design tools',
      'Create comprehensive development roadmap with sprint planning',
      'Auto-generate technical specifications and user stories',
      'Deploy prompts to multiple AI coding agents (GPT-o3, Claude Sonnet 4, Gemini 2.5 Pro)',
      'Execute parallel development streams (frontend, backend, database)',
      'Run automated testing suites (unit, integration, E2E)',
      'Deploy to app stores with metadata optimization and screenshot generation',
    ],
    tools: [
      { name: 'Figma API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6801.png' },
      { name: 'GitHub Actions', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6802.png' },
      { name: 'Docker', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6803.webp' },
      { name: 'Redis', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6804.png' },
      { name: 'Expo', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6805.png' },
    ],
    trigger: 'Project brief submission',
  },
  {
    id: 114,
    name: 'Make Game',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6806.png',
    category: 'Design & Develop',
    workflow: [
      'Initialize Three.js project with mobile optimization',
      'Generate procedural building system with physics engine',
      'Create touch control interface with gesture recognition',
      'Implement multiplayer networking infrastructure',
      'Generate terrain and asset libraries procedurally',
      'Build monetization system with in-app purchases',
      'Deploy cross-platform builds (iOS/Android) with cloud save integration',
    ],
    tools: [
      { name: 'Spline', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6806.png' },
      { name: 'Mobile SDKs', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6845.png' },
      { name: 'Alchemy API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6807.png' },
      { name: 'Cloud storage APIs', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6837.webp' },
    ],
    trigger: 'Game concept approval',
  },
  {
    id: 115,
    name: 'Send Email Campaign',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6808.png',
    category: 'Marketing',
    workflow: [
      'Segment customer database using behavioral and demographic data',
      'Generate personalized email templates with A/B testing variants',
      'Create dynamic content blocks based on user preferences',
      'Set up conditional trigger sequences (abandoned cart, birthday, etc.)',
      'Deploy multi-channel campaigns (email, SMS, push notifications)',
      'Monitor engagement metrics and auto-optimize send times',
      'Generate performance reports with ROI calculations',
    ],
    tools: [
      { name: 'Mailchimp API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6808.png' },
      { name: 'SendGrid', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6809.png' },
      { name: 'Customer.io', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6810.png' },
      { name: 'Analytics platforms' },
    ],
    trigger: 'Campaign brief or automated schedule',
  },
  {
    id: 116,
    name: 'Scrape Leads',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6811.png',
    category: 'Research/Scrape & Extract',
    workflow: [
      'Scrape directory websites and professional networks',
      'Extract contact information using pattern recognition',
      'Verify email addresses and phone numbers',
      'Enrich lead data with company information and social profiles',
      'Generate personalized outreach sequences for chatbot services',
      'Schedule and send emails with tracking and follow-up automation',
      'Monitor responses and update CRM with engagement data',
    ],
    tools: [
      { name: 'Scrapy', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6811.png' },
      { name: 'Hunter.io', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6812.webp' },
      { name: 'LinkedIn API' },
      { name: 'Mailchimp' },
    ],
    trigger: 'Lead generation quota requirement',
  },
  {
    id: 117,
    name: 'Analyze Financial',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6813.png',
    category: 'Finance',
    workflow: [
      'Connect to bank accounts via Plaid API with secure authentication',
      'Categorize transactions using ML classification algorithms',
      'Separate business expenses from personal income automatically',
      'Calculate tax deductibles and profit margins',
      'Generate interactive 3D visualizations using Three.js',
      'Create predictive cash flow models',
      'Export comprehensive HTML reports with drill-down capabilities',
    ],
    tools: [
      { name: 'Plaid API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6813.png' },
      { name: 'OpenAI GPT-4o', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6814.png' },
      { name: 'Three.js', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6815.webp' },
      { name: 'D3.js', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6816.png' },
      { name: 'Python financial libraries', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6838.png' },
    ],
    trigger: 'Monthly financial review cycle',
  },
  {
    id: 118,
    name: 'Make Trades',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6817.png',
    category: 'Finance',
    workflow: [
      'Monitor Tesla stock performance and market indicators',
      'Execute sell order for 10 shares when optimal conditions are met',
      'Analyze Apple stock volatility and technical indicators',
      'Place strategic put options with risk management parameters',
      'Monitor cryptocurrency markets for Fresh token performance',
      'Execute unstaking procedures and token swaps',
      'Purchase Fresh Force 1 NFT when available with bid optimization',
    ],
    tools: [
      { name: 'Alpaca API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6817.png' },
      { name: 'Coinbase Pro API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6818.png' },
      { name: 'OpenSea API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6839.png' },
      { name: 'TradingView alerts', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6819.png' },
    ],
    trigger: 'Market condition algorithms or manual override',
  },
  {
    id: 125,
    name: 'Optimize SEO',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6820.png',
    category: 'Content/Text',
    workflow: [
      'Research trending keywords and competitor analysis',
      'Generate blog article outlines with SEO optimization',
      'Create long-form content with internal linking strategies',
      'Optimize meta descriptions, headers, and image alt text',
      'Schedule publication across multiple platforms (WordPress, Medium)',
      'Create social media posts for Twitter/X and Substack',
      'Monitor performance metrics and adjust content strategy',
    ],
    tools: [
      { name: 'SEMrush API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6820.png' },
      { name: 'GPT-4o', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6814.png' },
      { name: 'WordPress API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6821.png' },
      { name: 'Buffer', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6822.png' },
      { name: 'Hootsuite', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6823.png' },
    ],
    trigger: 'Content calendar schedule or trending topic alerts',
  },
  {
    id: 126,
    name: 'Create Podcast',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6824.png',
    category: 'Content/Audio',
    workflow: [
      'Generate podcast script based on topic research and trending discussions',
      'Create AI-generated host dialogue with multiple voice personas',
      'Add background music, sound effects, and professional audio mixing',
      'Generate podcast artwork and episode thumbnails',
      'Upload to distribution platforms (Spotify, Apple Podcasts, Audible)',
      'Create show notes and transcriptions automatically',
      'Monitor analytics and optimize content based on listener engagement',
    ],
    tools: [
      { name: 'ElevenLabs', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6824.png' },
      { name: 'Descript', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6825.webp' },
      { name: 'Podcast hosting APIs' },
      { name: 'Spotify for Podcasters', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6840.webp' },
      { name: 'Apple Podcasts', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6841.png' },
    ],
    trigger: 'Content calendar or trending topic identification',
  },
  {
    id: 127,
    name: 'Generate Content',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6842.png',
    category: 'Social Media Reel',
    workflow: [
      'Research current hashtag trends and viral content patterns',
      'Generate script following formula: "Character action branded subject setting dialog action dialog"',
      'Create 3D rendered characters and branded product placement',
      'Generate realistic dialogue with emotion and timing',
      'Add trending music, effects, and platform-specific optimization',
      'Schedule posts across TikTok, Instagram Reels, YouTube Shorts',
      'Monitor performance and iterate successful content patterns',
    ],
    tools: [
      { name: 'Veo 3', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6842.png' },
      { name: 'RunwayML', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6827.png' },
      { name: 'TikTok', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6828.png' },
      { name: 'Instagram', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6830.png' },
      { name: 'Trend analysis tools' },
    ],
    trigger: 'Weekly content schedule or viral trend detection',
  },
  {
    id: 128,
    name: 'Create YouTube Video',
    type: 'file',
    parent_id: 16,
    icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6835.webp',
    category: 'YouTube Video',
    workflow: [
      'Research documentary topic with fact-checking and source verification',
      'Generate comprehensive script with narrative arc and educational value',
      'Create AI-generated narration with professional voice synthesis',
      'Source and generate relevant stock footage and B-roll content',
      'Add dynamic graphics, charts, and visual explanations',
      'Optimize for YouTube algorithm with keywords, thumbnails, and descriptions',
      'Monitor analytics and create follow-up content based on audience engagement',
    ],
    tools: [
      { name: 'Google gemini for research', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6835.webp' },
      { name: 'ElevenLabs for narration', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6824.png' },
      { name: 'Veo 3', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6842.png' },
      { name: 'Creatomate stitching', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6836.png' },
      { name: 'YouTube API', logo: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_6832.png' },
    ],
    trigger: 'Educational content calendar or trending tech topics',
  },
  { id: 119, name: 'Social Media Content', type: 'file', parent_id: 47, icon: '📱' },
  { id: 120, name: 'Email Campaign', type: 'file', parent_id: 47, icon: '📧' },
  { id: 121, name: 'Product Design', type: 'file', parent_id: 47, icon: '🎨' },
  { id: 122, name: 'Store Creation', type: 'file', parent_id: 47, icon: '🛍️' },
  { id: 123, name: 'App Development', type: 'file', parent_id: 47, icon: '💻' },
  { id: 124, name: 'App Store Publishing', type: 'file', parent_id: 47, icon: '🚀' },
  { id: 129, name: 'Commandr', type: 'file', parent_id: null, position_x: 220, position_y: 266, icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_1655.png', dark_icon: 'https://utdrojtjfwjcvuzmkooj.supabase.co/storage/v1/object/public/content//IMG_1654.png', url: 'https://commandr.co' },
];

let nextId = 131;

export class File {
  static async filter({ parent_id }) {
    if (parent_id === null) {
      // Only return items explicitly on the desktop
      return Promise.resolve(files.filter(file => file.parent_id === null));
    }
    return Promise.resolve(files.filter(file => file.parent_id === parent_id));
  }

  static async getAll() {
    return Promise.resolve(files);
  }

  static async update(id, data) {
    const fileIndex = files.findIndex(file => file.id === id);
    if (fileIndex !== -1) {
      files[fileIndex] = { ...files[fileIndex], ...data };
    }
    return files[fileIndex];
  }

  static async create(data) {
    const newFile = { ...data, id: nextId++ };
    files.push(newFile);
    return Promise.resolve(newFile);
  }

  static async delete(id) {
    files = files.filter(file => file.id !== id);
    return Promise.resolve();
  }
}
